name: Deploy Quartz site to GitHub Pages

# Allow only one concurrent deployment, skipping runs queued between the run
# in-progress and latest queued. However, do NOT cancel in-progress runs as we
# want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Run this workflow manually
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest # This job uses a GitHub-hosted runner.

    # Skip builds with "[ci skip]" in the commit
    if: "!contains(github.event.head_commit.message, '[ci skip]')"

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Pull content
        run: |
          rm -rf content
          git clone https://github.com/itspriddle/notes.git content
          rm -rf content/.git content/.github
      - name: Build site
        run: npx quartz build --bundleInfo
      - name: Write CNAME
        run: echo "notes.priddle.xyz" > content/CNAME
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: public

  # Deployment job
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
